// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA96buLXZdhEijVO4q6Qtls5ZfMQOxgYpE',
    appId: '1:604148632550:web:c1660fa7723f99ba4d2427',
    messagingSenderId: '604148632550',
    projectId: 'elderzha-da434',
    authDomain: 'elderzha-da434.firebaseapp.com',
    storageBucket: 'elderzha-da434.firebasestorage.app',
    measurementId: 'G-LS6GDBMEP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3TvYgGYbRR71EaHFytZddgbQKYZmgFUg',
    appId: '1:604148632550:android:6f871460dd04533d4d2427',
    messagingSenderId: '604148632550',
    projectId: 'elderzha-da434',
    storageBucket: 'elderzha-da434.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ6Fd1R2Nve8agjDuupt3ZKITCIGJhQ_Y',
    appId: '1:604148632550:ios:d72ab656a540428f4d2427',
    messagingSenderId: '604148632550',
    projectId: 'elderzha-da434',
    storageBucket: 'elderzha-da434.firebasestorage.app',
    iosBundleId: 'com.reminder.customer',
  );

}
